### PR TITLE
SDK-1329 SDK layout update

### PR DESCRIPTION
**Pull request by echo-branch**
## Reference
SDK-1329 SDK layout update

## Summary
The Branch SDK has a usual project layout which causes a large number of warnings when using SPM. The root cause is the Branch header is being used as the framework umbrella header and a class header.

There are a few more minor issues also being addressed with this change.

## Type Of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Testing Instructions
Test integration options.
1. SPM - umbrella header warnings should be gone.
2. Cocoapods
3. Carthage
4. Manual xcframework

Confirm TestBed unit tests still work.

Confirm development is not hindered by the changes.

cc @BranchMetrics/saas-sdk-devs for visibility.

### CODE REVIEW

**Comment by ahmednawar** [comment]
@echo-branch can you investigate why the unit tests are failing?

**Comment by nsingh-branch** [comment]
When running the tests locally, I had one test fail, `testEvent` in `BranchEvent.Test`. Look's like the AssertEqualObjects was failing because `skan_time_window: 5184000.000000` in `V2EventJSON` needed to be updated to `86400.000000`.

**Comment by ahmednawar** [comment]
@nsingh-branch @ndixit-branch now that we are out of the spike mode, can you please review this PR. Would like to get it out next week.

@echo-branch can you please look into the failing unit tests?

**Comment by nsingh-branch** [comment]
Integration and development seem to still be working well. The only changes i found I needed to do were changing the podfile and import statements to BranchSDK. 
Although I'm still experiencing those two tests failures, even on different fresh devices.

**Review by nsingh-branch — APPROVED** [review]

**Comment by gabrieldl** [comment]
Should this still be marked as WIP?

**Review by NidhiDixit09 — APPROVED** [review]
Code structure looks good. All unit tests passed. Sample App compilation was also successful after updating framework name in import statements. In Integration tests with Carthage for tvOS I found few headers missing from the .xcframework. However with iOS all Branch SDK Integration (installation) methods passed.

**Pull request merged**
