### PR TITLE
[SDK-1774] Update iOS Testbed

### PR DESCRIPTION
**Pull request by nsingh-branch**
## Reference
SDK-1744 -- [iOS] Update iOS Testbed

## Summary
Updated the UI, removed old functions, and added new functions to the testbed. 

## Motivation
The old testbed UI became dated and some of the functionality was either deprecated or missing.

## Type Of Change

- [x] New feature (non-breaking change which adds functionality)

## Testing Instructions
Run the testbed and try the various methods through the buttons.

cc @BranchMetrics/saas-sdk-devs for visibility.

### CODE REVIEW

**Comment by ahmednawar** [comment]
@nsingh-branch what's the next step here?

**Comment by nsingh-branch** [comment]
> @nsingh-branch what's the next step here?

@ahmednawar We were waiting for the 2.0.0 release, now it just needs review/feedback and then its ready for release.

**Comment by ahmednawar** [comment]
Ok, please work with the team to review and ship it.

**Comment by nsingh-branch** [comment]
> this has been sitting idle for a very long time.

It's still in review, but i believe some INTENG's have taken priority. Also there seems to be an issue with the tests timing out in GHA.

**Review by echo-branch — APPROVED** [review]

**Pull request merged**
