### PR TITLE
SDK-1111 support error return for latd method

### PR DESCRIPTION
**Pull request by justinfurstossbranch**
Please submit your PR against the `staging` branch.

### CODE REVIEW

**Comment by echo-branch** [comment]
@justinfurstossbranch 
The class code change looks good, but the public API needs to be updated to match the change or a new API with error is required. 

https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/Branch.m#L1288-L1293

**Comment by justinfurstossbranch** [comment]
@echo-branch 
So i updated the latd method in Branch.m to handle the additional error return.

In regards to the public API. On Android we are able to support this :https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/master/Branch-SDK/src/main/java/io/branch/referral/ServerRequestGetLATD.java#L86 
and they seem to be hitting the same endpoint: 
Android: https://github.com/BranchMetrics/android-branch-deep-linking-attribution/blob/master/Branch-SDK/src/main/java/io/branch/referral/Defines.java#L245
iOS: https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/blob/master/Branch-SDK/BranchConstants.m#L86

**Comment by echo-branch** [comment]
Yea, I was referring to the SDK public API not the class public API.  Should have been clearer on that.

**Comment by justinfurstossbranch** [comment]
Alright sweet! So my recent commit addresses that https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/pull/1084/commits/5202ece9ae1a7ba0a3bb1cfb11ca9cb798406c88 

Thanks @echo-branch !

**Pull request merged**
