### PR TITLE
SDK-1450 copy over PR from SPM repo

### PR DESCRIPTION
**Pull request by echo-branch**
Thanks soumyamahunt!

A long forgotten PR to the SPM repo. I keep forgetting about.
https://github.com/BranchMetrics/ios-branch-sdk-spm/pull/6

### CODE REVIEW

**Review by Deloww — COMMENTED** [review]
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/pull/1177/files

**Review by Deloww — APPROVED** [review]
https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/pull/1177/files

**Review by nsingh-branch — APPROVED** [review]

**Comment by Deloww** [comment]
Package.swift

**Review by Deloww — COMMENTED** [review]
Package.swift

**Pull request merged**
