### PR TITLE
iOS Integration Validator Bugfix (for client<>server URI scheme check)

### PR DESCRIPTION
**Pull request by rob-gioia-branch**
## Reference
No ticket - this was confusing clients, so I wanted to fix this.

## Summary
Currently, our iOS integration validator would check for the Branch URI scheme as the first URI scheme in the list (apart from a few like facebook, etc... that are hardcoded for it to skip when checking). The new code fixes this issue by looping through each of the URI schemes so that Branch doesn't have to be the first URI scheme in the list for the integration validator to pass.

## Motivation
This was confusing clients. 

To see an example of this issue, please view the Master ProServe iOS Branch `example-of-uri-scheme-bug` (Link: https://github.com/BranchMetrics/Master-Proserve-iOS/tree/example-of-uri-scheme-bug)

I added `psmaster0`, an incorrect URI scheme, at index 0. 

Screenshot 2023-10-23 at 10 10 46 AM

This caused the integration validator check for the URI scheme to fail, even though the correct URI scheme of `psmaster` was in the list right below it. 

Screenshot 2023-10-20 at 4 21 03 PM

With the changes in this PR, the issue is fixed by checking if the correct URI scheme is present **_anywhere_** in the list

Screenshot 2023-10-23 at 10 04 46 AM

## Type Of Change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Testing Instructions
To test this, do one of the following:
- Test the Master ProServe iOS branch I put together where I recreated the bug and then used this sample code to fix it (Link: https://github.com/BranchMetrics/Master-Proserve-iOS/tree/integration-validator-uri-fix-test)
- Utilize your own sample app. Add an incorrect URI scheme (one other than the one you have on your Branch dashboard) as Item 0 in the list. If you run the integration validator, notice the fail message. Then add the code from this PR and observe the issue is fixed.

cc @BranchMetrics/saas-sdk-devs for visibility.

### CODE REVIEW

**Comment by ahmednawar** [comment]
@rob-gioia-branch is this PR still valid? Do you need someone to review?

**Comment by ahmednawar** [comment]
@NidhiDixit09 can you please review this PR?

**Review by NidhiDixit09 — COMMENTED** [review]
I have validated fix with my test app and adding some random url schemes. Fix looks good to me.

**Review by NidhiDixit09 — APPROVED** [review]

**Comment by rob-gioia-branch** [comment]
> I have validated fix with my test app and adding some random url schemes. Fix looks good to me.

Thanks @NidhiDixit09 ! Do you have recommendations on fixing the merge conflicts so that this can be merge into master? Thanks!

cc: @ahmednawar

**Comment by NidhiDixit09** [comment]
@rob-gioia-branch I have merged master into this branch and we dont have any conflicts now.

**Comment by rob-gioia-branch** [comment]
> @rob-gioia-branch I have merged master into this branch and we dont have any conflicts now.

Merged, thanks @NidhiDixit09 ! I appreciate the help

**Pull request merged**
